### ISSUE TITLE
DzVents change 'opmode' only possible for level 10 and 20

### ISSUE THREAD

**Issue by rivertechnology** [guillaumezin/DomoticzEbusd#17]
Hi,

Thanks for solving my previous DzVents and Ebusd plugin issue. In my DzVents program I want to change the z1opmode or hwcopmode with .switchSelector().

At default by adding an 'opmode' device I got 4 options: 'off,auto,day,night' my thermostat has only 3 options: 'off, timeshedule,manual'.
I've changed the options and with the UI it works fine :-).

![afbeelding](https://github.com/user-attachments/assets/c8b67ca6-a3cf-406d-b5af-aedbb86cb842)

But by using DzVents, automatic change to 'off' ;.switchSelector(10) or .switchSelector('off') works and .switchSelector(20) also works, but a change to level 30 (or manual) doesn't work...

I've tried it for my hwcopmode and z1opmode both have the same issue,

Thanks in advance for the help.

**Comment by guillaumezin** [comment]
Hello,
Do you mean that you edited the switch to change level names, for both hwcopmode and z1opmode? Could you post a screen capture of the device when you click "Edit"? I'm not sure you can edit level number and level name as you did, because the plugin and ebusd daemon is not aware of this change. If they are not correct, you have to change ebusd csv config files...

**Comment by guillaumezin** [comment]
I did a few tries and even when not changing levels, that's strange on my side too, the switchSelector() dzVent function seems buggy...

**Comment by guillaumezin** [comment]
I think I found the problem. Do you still have the problem if you rename level 0 as "Off" for instance then save?
