### ISSUE TITLE
Question : Installation planning and Ebusd configuration file

### ISSUE THREAD

**Issue by barrydouu** [guillaumezin/DomoticzEbusd#18]
Hello

I've just order an ebus adapter. I did not receive it until now so I'm planning the ebusd installation in docker mode. 

I've seen that a volume map to "/opt/config" in docker is needed. But I don't understand if I need to clone the ebusd-configuration git respository on this location. Is the ebusd that do it automatically when it detect a boiler ?

Thank you for your help

**Comment by guillaumezin** [comment]
Hello,
This is not mandatory, ebusd will automatically load configuration files from Internet when configpath is not set (it's the case in the docker-compose.yml files examples), but this way you can review and edit them if needed, or add other config files if necessary (for instance I added "- EBUSD_MQTTINT=/opt/config/mqtt-domoticz.cfg" to docker-compose.yml and put mqtt-domoticz.cfg under config/ for some tests I did).

**Comment by barrydouu** [comment]
Thank you for the answer

I still have questions :)  
I have quite the same boiler as yours : VUW FR 306/5-5 R2 and calormatic 470f. No VR61, I have only one heating circuit. Did you need to modify the config file ?
And if I create the folder, does EBusd download the file in this location, or do I need to explicitly put the file here ?

I understand with your comment about MQTT that you have tried to integrate ebusd to domoticz with mqtt. It was my first thought, before I found your plugin. So I wonder why it's not working with MQTT ?

**Comment by guillaumezin** [comment]
> I still have questions :) I have quite the same boiler as yours : VUW FR 306/5-5 R2 and calormatic 470f. No VR61, I have only one heating circuit. Did you need to modify the config file ? And if I create the folder, does EBusd download the file in this location, or do I need to explicitly put the file here ?

You should have nothing to do, ebusd will autodiscover everything and create directory and download config files accordingly.

> I understand with your comment about MQTT that you have tried to integrate ebusd to domoticz with mqtt. It was my first thought, before I found your plugin. So I wonder why it's not working with MQTT ?

I began this plugin because I found MQTT configuration cumbersome. Then some autodiscovery mechanism were added, to ease MQTT configuration, so I thought I would give up the plugin, but even with MQTT autodiscovery, there are still a lot of very complex configuration to do, for instance to deal with date and time, so I went back to this plugin, I find it much easier to use for ebus, except for https://github.com/guillaumezin/DomoticzEbusd?tab=readme-ov-file#particular-case-of-holiday-mode but it would be the same mess with MQTT anyway.

By the way I still have 2 PCB (without components) of https://www.mikrocontroller.net/topic/346833?page=single I can send from France if you pay for the stamp. The adapter I made from this works perfectly since years.

**Comment by barrydouu** [comment]
Thanks again for your help

I've seen the holiday case, but as you tell, it will be the same with MQTT I think. And the script is quite simple. Managing holiday is one of the reason I search how to connect my boiler.

I'm french too, but I already have order my ebus adapter. I'm just waiting for the shipment. It's this one : https://adapter.ebusd.eu/index.en.html
