### ISSUE TITLE
Changing parameter in ebusd configuration from read only to writable does not change domoticz instance

### ISSUE THREAD

**Issue by arjaniv** [guillaumezin/DomoticzEbusd#4]
line 527
`                            
                        # check if device is already in domoticz database, based on deviceid
                        bFound = False
                        for iIndexUnit, oDevice in Devices.items():
                            # .lower() for backward compatibility
                            if oDevice.DeviceID.lower() == sDeviceIntegerID:
                                # log device found, with dFieldDefs["comment"] giving hints on how to use register
                                Domoticz.Log("Device " + oDevice.Name + " unit " + str(iIndexUnit) + " and deviceid " + sDeviceID + " detected: " + dFieldDefs["comment"])
                                # if found, continue loop to next item
                                bFound = True
                                break
`

does not update read/write status for devices already in the database.

Maybe not a big problem, but it took a while for me to found out why the quickveto temp and hc1SFmode could not be changed in domoticz

**Comment by guillaumezin** [comment]
Hi,

Thank you for reporting this. This is not an obvious decision however, because it means that I need to force the type, the subtype and the switchtype of devices at each plugin boot for devices already in database and handled by the plugin. Meaning that if a user changed the button switch type, it will fall back to default forced by the plugin. I have to test it to see if it has side effects.

**Comment by guillaumezin** [comment]
Could you try version 1.3.0?
